### ISSUE TITLE
Unknown type kind

### ISSUE THREAD

**Issue by pascaldekloe** [jessevdk/cldoc#126] opened 2017-08-05 21:46 UTC
Generation fails and the error message ain't great either for the following file.

https://github.com/pascaldekloe/colfer/blob/master/c/gen/Colfer.c

```
% cldoc generate -std=c11 -x c -- --output doc Colfer.h 
Processing Colfer.h
Traceback (most recent call last):
  File "/Users/pascal/Library/Python/2.7/bin/cldoc", line 11, in <module>
    sys.exit(run())
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/cmdgenerate.py", line 125, in run
    t.process()
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/tree.py", line 212, in process
    self.visit(tu.cursor.get_children())
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/tree.py", line 517, in visit
    self.visit(item.get_children(), node)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/tree.py", line 502, in visit
    node = cls(item, None)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/nodes/field.py", line 23, in __init__
    self.type = Type(cursor.type, cursor=cursor)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/nodes/ctype.py", line 58, in __init__
    self._kind = tp.kind
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/clang/cindex.py", line 1627, in kind
    return TypeKind.from_id(self._kind_id)
  File "/Users/pascal/Library/Python/2.7/lib/python/site-packages/cldoc/clang/cindex.py", line 1519, in from_id
    raise ValueError,'Unknown type kind %d' % id
ValueError: Unknown type kind 119
```

**Comment by topisani** [comment] 2017-08-30 15:34
same exact problem here. does anyone know why?

**Comment by wtbarnes** [comment] 2017-09-16 04:24
I'm also having this exact same issue. 

- **OS:** Mac OS X 10.12.6 (sierra)
- **python:** 2.7
- **cldoc:** 1.9
- **clang:** 5.0.0

**Comment by troelsfr** [comment] 2018-01-20 21:53
The underlying issue (for me at least) seems to be when you use nested classes

`class Foo {
  class Bar {
    // ...
  };
  std::vector< Bar > bars_;
public:
   // ...
};`

I can confirm that this issue is resolved in the latest repository version as @wtbarnes says in his comment.

**Comment by jessevdk** [comment] 2018-04-01 23:12
New version has been released that should resolve this.

**Closed by jessevdk** 2018-04-01 23:12 UTC
